services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_USER=${PG_USERNAME}
      - DB_PASS=${PG_PASSWORD}
    env_file: .env
    
  crud-service:
    build:
      context: ./crud-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_USER=${PG_USERNAME}
      - DB_PASS=${PG_PASSWORD}
    env_file: .env