spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/dev_db
  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate-format-sql: true
  logging:
    level:
      org.springframework.security: DEBUG