spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PG_URL:localhost}:${PG_PORT:5433}/${PG_DATABASE:taskdb}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect