spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PG_URL:localhost}:${PG_PORT:5432}/${PG_DATABASE:basedb}
    driverClassName: org.postgresql.Driver
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect