spring:
  application:
    name:
      baseproject
  profiles:
    active: dev

server:
  port: 8080
  api:
    doc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui
