services:
  app:
    image: vasilev/taskmanager:0.0.1-SNAPSHOT
    container_name: taskmanager
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - tmdb:/var/lib/postgresql/data
volumes:
  tmdb:
    name: tmdb