services:
  app:
    image: vasilev/taskmanager:0.0.1-SNAPSHOT
    container_name: taskmanager
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE:tmdb}
      POSTGRES_USER: ${PG_USERNAME:postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:postgres}
    ports:
      - "5432:5432"