services:
  app:
    image: vasilev/taskmanager:0.0.1-SNAPSHOT
    container_name: taskmanager
    environment:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - tmdb:/var/lib/postgresql/data
volumes:
  tmdb:
    name: tmdb